### ISSUE TITLE
Running twice

### ISSUE THREAD

**Issue by seehad** [james2m/seedbank#50] opened 2015-04-01 03:22 UTC
I have exactly one seed file at the moment to create a default user.  It is located in  /db/seeds/01-users.seeds.rb

------- contents of file below

# 01 - users.seeds.rb

puts "------ 01 - users.seeds.rb"

User.create(email: 'peter@nevernever.com', \
  password: 'secret', password_confirmation: 'secret', \
  admin: true, can_be_deleted: false )

----- end contents

When I run rake db:seed it is running twice.  Any idea as to why?  I'm running 0.3.0 with ruby 2.2.1 and rails 4.1.

**Comment by james2m** [comment] 2015-04-01 04:47
Give 0.4.0.pre a try.

**Comment by edwinhorneij** [comment] 2015-08-04 16:46
We're seeing the same thing. It looks like all seed files are being executed twice. We tried using v0.4.0pre and got the same behavior.

**Comment by brenes** [comment] 2015-09-02 10:29
Any update on this? 

I'm having the same issue with v0.4.0pre

**Comment by james2m** [comment] 2015-09-02 17:01
I'll try and get to it next week, but exceptionally busy. If anyone can give me a test project and dome debugging insights it'd be really useful. 

J.

**Comment by davidimoore** [comment] 2015-09-29 21:02
Has anyone looked into this. I'm guessing this commit might be a good place to start athttps://github.com/james2m/seedbank/commit/1100360765f04c4bef36b7bb7321ae89969c9c04

**Comment by james2m** [comment] 2015-09-30 03:10
@davidimoore That just stops it being defined again on re-invocation, but each Rake task is marked as already_invoked on execution. So they don't actually run a 2nd time unless they are re-enabled.

I've never been able to reproduce this and nobody has given me anything useful to debug so I don't see this going away without an example project to look at.

**Comment by davidimoore** [comment] 2015-09-30 14:24
@james2m I wish I could share the repo I'm having the issue with presently but I don't have that option. 

I'll generate a couple of apps this weekend and attempt to reproduce to see what happens.

**Comment by james2m** [comment] 2015-10-01 08:54
Cool. I've tried to reproduce on 6 different apps and never succeeded. Must be something in the way I set them up. Rake and ruby version would help too. 

 Thanks.

**Comment by davidimoore** [comment] 2015-10-14 20:34
@james2m Sorry just following up. I tried as well with a new app and couldn't reproduce. I haven't tried after adding the ActiveAdmin or Devise gems which were present in the app that I had the initial issue with. I'll try to find time to do further testing.

**Comment by james2m** [comment] 2015-10-15 03:03
Thanks for the follow up. If anybody comes up with some reproducible code I’ll take a look.

**Comment by vortizhe** [comment] 2015-12-07 22:33
I was having the same issue with v0.4.0pre, but I realize the task was loading twice. 

This require was in Rakefile by mistake:

```
require 'seedbank'
Seedbank.load_tasks if defined?(Seedbank)
```

After removed runs like a charm.

**Comment by davidimoore** [comment] 2015-12-07 22:58
This issue occurs for me without the Rakefile require and load_tasks method being called.

**Comment by Ganasist** [comment] 2016-01-05 11:21
@vortizhe has the fix, I just removed those lines from the Rakefile and it runs once. Perhaps the docs should be updated, if this is the only issue?

**Comment by james2m** [comment] 2016-01-05 12:11
Think I'll close this as @vortizhe has the fix and @Ganasist has verified it.

**Closed by james2m** 2016-01-05 12:11 UTC
